### PR TITLE
PPJ support and pre-scan namespace resolution

### PR DESCRIPTION
**Pull request by nikitalita**
This implements PPJ support and pre-scanning non-PCompiler/PPJ input files for namespace resolution.

So basically, we have two different namespace resolution schemes:

"""classic""" mode:
- applies to inputs from PPJ, or if we're in PCompiler compatibility mode
- input files can be absolute or relative to any of the import directories
- namespaces are determined by the relative basedir from the input file to the import directory 
- so "C:/Scripts/autoloot/fragments/terminals/something.psc" and an import directory of "C:/Scripts" ends up with an object name of "autoloot:fragments:terminals:something"

Modern mode:
- applies to all other inputs
- input files are either absolute or relative to the CWD
- the files are pre-scanned for their proper object names.

We probably want to do a refactor on the compiler nodes to have it split into two separate things; a Read/pre-parse node and everything else, since the input params for the nodes get modified after the namespace has been resolved

### CODE REVIEW

**Comment by nikitalita** [comment]
We probably want to remove the cwd from the default imports if we’re in modern mode; there’s no longer a need for it and it can lead to unexpected behavior.

**Review by Orvid — APPROVED** [review]

**Comment by qudix** [comment]
Anyone still alive?

**Comment by Gamerooni** [comment]
Thank you so much!

**Comment by Gamerooni** [comment]
this might solve the build issue:
https://github.com/microsoft/vcpkg/issues/38980#issuecomment-2138632860

**Pull request merged**
